# Generated by Django 3.0.5 on 2023-09-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
