# Generated by Django 4.2.5 on 2023-09-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0017_subsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsubcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.category'),
        ),
    ]
