# Generated by Django 4.2.5 on 2023-10-05 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0019_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.carmodel')),
            ],
        ),
    ]
