# Generated by Django 4.2.5 on 2023-10-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0022_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='phone_number',
            new_name='Alternative_mobile',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_service_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
