# Generated by Django 4.2.5 on 2023-10-09 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0024_alter_booking_selected_service_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='selected_service_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_subsubcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.subsubcategory'),
        ),
    ]
