# Generated by Django 4.2.6 on 2023-10-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0025_alter_booking_selected_service_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='category',
        ),
        migrations.RemoveField(
            model_name='request',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='request',
            name='date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='problem_description',
        ),
        migrations.RemoveField(
            model_name='request',
            name='vehicle_brand',
        ),
        migrations.RemoveField(
            model_name='request',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='request',
            name='vehicle_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='vehicle_no',
        ),
        migrations.AddField(
            model_name='request',
            name='Alternative_mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='appointment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
