# Generated by Django 4.2.6 on 2023-10-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0026_remove_request_category_remove_request_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='Alternative_mobile',
        ),
        migrations.RemoveField(
            model_name='request',
            name='address',
        ),
        migrations.RemoveField(
            model_name='request',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='request',
            name='name',
        ),
        migrations.AddField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('two wheeler with gear', 'two wheeler with gear'), ('two wheeler without gear', 'two wheeler without gear'), ('three wheeler', 'three wheeler'), ('four wheeler', 'four wheeler')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='cost',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='request',
            name='problem_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='vehicle_brand',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='vehicle_model',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='vehicle_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='vehicle_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
