# Generated by Django 4.2.6 on 2023-10-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0027_remove_request_alternative_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
