# Generated by Django 4.2.6 on 2023-10-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0029_remove_booking_selected_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_service_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
