# Generated by Django 4.2.6 on 2023-10-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0030_booking_selected_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='selected_service_image',
        ),
    ]
