# Generated by Django 4.2.6 on 2023-10-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0031_remove_booking_selected_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True),
        ),
    ]
