# Generated by Django 4.2.6 on 2023-10-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0036_alter_booking_status'),
        ('vehicle', '0036_booking_customer'),
    ]

    operations = [
    ]
