# Generated by Django 4.2.6 on 2023-10-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0038_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.carmodel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_car_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.carname'),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.type'),
        ),
    ]
