# Generated by Django 4.2.6 on 2023-10-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0039_booking_selected_car_model_booking_selected_car_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash on Service'), ('Online', 'Online Pay')], max_length=10, null=True),
        ),
    ]
