# Generated by Django 4.2.6 on 2023-10-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0044_booking_payment_status_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
    ]
