# Generated by Django 4.2.6 on 2023-10-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0046_remove_customer_address_remove_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='job_title',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('painter', 'Painter'), ('Tester', 'Tester'), ('Operator', 'Operator')], default='select title', max_length=20),
        ),
    ]
