# Generated by Django 4.2.6 on 2023-10-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0047_alter_mechanic_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
