# Generated by Django 4.2.6 on 2023-10-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0048_customer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
    ]
