# Generated by Django 4.2.6 on 2023-10-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0049_remove_customer_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
