# Generated by Django 4.1.2 on 2023-09-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
