# Generated by Django 3.0.5 on 2023-09-19 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20230918_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Mechanic'),
        ),
    ]
